## Neural Network - Back Propagation

In [0]:
import numpy as np

In [7]:
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
print(X)

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]


In [5]:
wh = np.around(np.random.random((4,3)),decimals=2)
print(wh)

array([[0.66, 0.5 , 0.61],
       [0.49, 0.68, 0.08],
       [0.05, 0.62, 0.68],
       [0.5 , 0.37, 0.85]])

In [6]:
bh = np.around(np.random.random((1,3)),decimals=2)
print(bh)

[[0.16 0.74 0.65]]


In [8]:
hidden_layer_input = np.dot(X,wh) + bh
print(hidden_layer_input)

[[0.87 1.86 1.94]
 [1.37 2.23 2.79]
 [1.15 1.79 1.58]]


In [26]:
def sigmoid(x):
    return 1 / (1 + np.e ** -x)
  
hiddenlayer_activations=np.around(sigmoid(hidden_layer_input),2)

print(hiddenlayer_activations)

[[0.7  0.87 0.87]
 [0.8  0.9  0.94]
 [0.76 0.86 0.83]]


In [10]:
wout = np.around(np.random.random((3,1)),decimals=2)
print(wout)

[[0.95]
 [0.19]
 [0.81]]


In [11]:
bout = np.around(np.random.random((1,1)),decimals=2)
print(bout)

[[0.96]]


In [13]:
output_layer_input = np.dot(hiddenlayer_activations,wout) + bout
print(output_layer_input)

[[2.495 ]
 [2.6524]
 [2.5177]]


In [14]:
output=np.around(sigmoid(output_layer_input),2)
print(output)

[[0.92]
 [0.93]
 [0.93]]


In [15]:
y = np.array([[1],[1],[0]])
print(y)

[[1]
 [1]
 [0]]


In [16]:
E = y-output
print(E)

[[ 0.08]
 [ 0.07]
 [-0.93]]


In [17]:
def derivatives_sigmoid(x):
    return (sigmoid(x) * (1-sigmoid(x)))
  
Slope_output_layer= np.around(derivatives_sigmoid(output),2)

Slope_hidden_layer= np.around(derivatives_sigmoid(hiddenlayer_activations),2)

print(Slope_output_layer)

print(Slope_hidden_layer)

[[0.2]
 [0.2]
 [0.2]]
[[0.22 0.21 0.21]
 [0.21 0.21 0.2 ]
 [0.22 0.21 0.21]]


In [18]:
learning_rate = 0.1
d_output = E * Slope_output_layer * learning_rate

print(d_output)

[[ 0.0016]
 [ 0.0014]
 [-0.0186]]


In [19]:
Error_at_hidden_layer = np.dot(d_output, np.transpose(wout))
print(Error_at_hidden_layer)

[[ 0.00152   0.000304  0.001296]
 [ 0.00133   0.000266  0.001134]
 [-0.01767  -0.003534 -0.015066]]


In [20]:
d_hiddenlayer = Error_at_hidden_layer * Slope_hidden_layer
print(d_hiddenlayer)

[[ 3.34400e-04  6.38400e-05  2.72160e-04]
 [ 2.79300e-04  5.58600e-05  2.26800e-04]
 [-3.88740e-03 -7.42140e-04 -3.16386e-03]]


In [21]:
wout = wout + np.dot(np.transpose(hiddenlayer_activations), d_output) * learning_rate
print(wout)

[[0.9488104]
 [0.1886656]
 [0.808727 ]]


In [22]:
wh = wh + np.dot(np.transpose(X),d_hiddenlayer) * learning_rate
print(wh)

[[0.66006137 0.50001197 0.6100499 ]
 [0.48961126 0.67992579 0.07968361]
 [0.05006137 0.62001197 0.6800499 ]
 [0.49963919 0.36993137 0.84970629]]


In [23]:
bh = bh + np.sum(d_hiddenlayer, axis=0) * learning_rate
print(bh)

[[0.15967263 0.73993776 0.64973351]]


In [24]:
bout = bout + np.sum(d_output, axis=0) * learning_rate
print(bout)

[[0.95844]]
